import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/components/goods/GoodsmallDetail.tsx
import { useParams } from "react-router-dom";
import { useState } from "react";
import { goodsList } from "../../data/goodsData";
import "./GoodsmallDetail.css";
export default function GoodsmallDetail() {
    const { id } = useParams();
    const product = goodsList.find((item) => item.id === id);
    // 선택된 이미지 상태
    const [mainImage, setMainImage] = useState(product?.images[0] ?? "");
    if (!product)
        return _jsx("div", { children: "\uC0C1\uD488\uC744 \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4." });
    return (_jsxs("div", { className: "goods-detail-page", children: [_jsxs("div", { className: "goods-top-area", children: [_jsxs("div", { children: [_jsx("img", { src: mainImage, alt: product.name, className: "main-product-image" }), _jsx("div", { className: "thumbnail-list", children: product.images.map((img, idx) => (_jsx("img", { src: img, alt: `${product.name} 썸네일 ${idx + 1}`, className: `thumbnail-image ${mainImage === img ? "active" : ""}`, onClick: () => setMainImage(img) }, idx))) })] }), _jsxs("div", { className: "goods-info-area", children: [_jsx("h2", { className: "goods-detail-name", children: product.name }), _jsxs("div", { className: "goods-info-table", children: [_jsxs("div", { className: "goods-info-row", children: [_jsx("div", { className: "goods-info-label", children: "\uD310\uB9E4\uAC00" }), _jsxs("div", { className: "goods-info-value", children: [product.price.toLocaleString(), "\uC6D0"] })] }), _jsxs("div", { className: "goods-info-row", children: [_jsx("div", { className: "goods-info-label", children: "\uBC30\uC1A1\uBC29\uBC95" }), _jsx("div", { className: "goods-info-value", children: "\uD0DD\uBC30" })] }), _jsxs("div", { className: "goods-info-row", children: [_jsx("div", { className: "goods-info-label", children: "\uBC30\uC1A1\uBE44" }), _jsx("div", { className: "goods-info-value", children: "3,000\uC6D0" })] }), _jsxs("div", { className: "goods-info-row", children: [_jsx("div", { className: "goods-info-label", children: "\uC635\uC158" }), _jsx("div", { className: "goods-info-value", children: _jsxs("select", { className: "goods-option-select", defaultValue: "", children: [_jsx("option", { value: "", disabled: true, children: "- [\uD544\uC218] \uC635\uC158\uC744 \uC120\uD0DD\uD574 \uC8FC\uC138\uC694 -" }), _jsx("option", { value: "opt1", disabled: true, children: "\uC0C1\uD488\uBA851 (\uD488\uC808)" }), _jsx("option", { value: "opt2", disabled: true, children: "\uC0C1\uD488\uBA852 (\uD488\uC808)" }), _jsx("option", { value: "opt3", disabled: true, children: "\uC0C1\uD488\uBA853 (\uD488\uC808)" })] }) })] })] }), _jsx("p", { className: "goods-detail-notice", children: "\u203B \uBAA8\uB4E0 \uC0C1\uD488\uC740 \uD488\uC808 \uC0C1\uD0DC\uC785\uB2C8\uB2E4." }), _jsxs("div", { className: "goods-total-section", children: [_jsx("div", { className: "goods-total-label", children: "\uCD1D \uAE08\uC561" }), _jsx("div", { className: "goods-total-price", children: "0\uC6D0" })] }), _jsx("button", { className: "goods-detail-soldout", disabled: true, children: "SOLD OUT" })] })] }), _jsx("div", { className: "goods-extra-section", children: _jsx("img", { src: product.detailimage, alt: `${product.name} 상세` }) })] }));
}
